start cmd /k "cd Acidity Customs && rclone sync -P --exclude *.ini --exclude *.rating --exclude *.bat --exclude *.json --exclude *.optkr acidcustoms:/ . && exit"
start cmd /k "cd Arcaea && rclone sync -P --exclude *.ini --exclude *.rating --exclude *.bat --exclude *.json --exclude *.optkr arcaea:/ . && exit"
start cmd /k "cd Berdstep's Custom Charts && rclone sync -P --exclude *.ini --exclude *.rating --exclude *.bat --exclude *.json --exclude *.optkr berdcustoms:/ . && exit"
start cmd /k "cd Bol Customs && rclone sync -P --exclude *.ini --exclude *.rating --exclude *.bat --exclude *.json --exclude *.optkr bolcustoms:/ . && exit"
start cmd /k "cd Clover's Charts && rclone sync -P --exclude *.ini --exclude *.rating --exclude *.bat --exclude *.json --exclude *.optkr clover:/ . && exit"
start cmd /k "cd Colin Customs && rclone sync -P --exclude *.ini --exclude *.rating --exclude *.bat --exclude *.json --exclude *.optkr colincustoms:/ . && exit"
start cmd /k "cd DiamondN1nja Charts && rclone sync -P --exclude *.ini --exclude *.rating --exclude *.bat --exclude *.json --exclude *.optkr diamondcustoms:/ . && exit"
start cmd /k "cd DragonRatTiger Customs && rclone sync -P --exclude *.ini --exclude *.rating --exclude *.bat --exclude *.json --exclude *.optkr drtcustoms:/ . && exit"
start cmd /k "cd GuivenYong's Charts && rclone sync -P --exclude *.ini --exclude *.rating --exclude *.bat --exclude *.json --exclude *.optkr guivenyong:/ . && exit"
start cmd /k "cd Makotora Customs && rclone sync -P --exclude *.ini --exclude *.rating --exclude *.bat --exclude *.json --exclude *.optkr makotoracustoms:/ . && exit"
start cmd /k "cd Megi's Charts && rclone sync -P --exclude *.ini --exclude *.rating --exclude *.bat --exclude *.json --exclude *.optkr megicustoms:/ . && exit"
start cmd /k "cd Meow Customs && rclone sync -P --exclude *.ini --exclude *.rating --exclude *.bat --exclude *.json --exclude *.optkr meowcustoms:/ . && exit"
start cmd /k "cd Monogatari Pack && rclone sync -P --exclude *.ini --exclude *.rating --exclude *.bat --exclude *.json --exclude *.optkr monogataripack:/ . && exit"
start cmd /k "cd Moshir's Charts && rclone sync -P --exclude *.ini --exclude *.rating --exclude *.bat --exclude *.json --exclude *.optkr moshirmoshir:/ . && exit"
start cmd /k "cd Nabix's TACO CHARTZ && rclone sync -P --exclude *.ini --exclude *.rating --exclude *.bat --exclude *.json --exclude *.optkr nabix:/ . && exit"
start cmd /k "cd Phigros Pack && rclone sync -P --exclude *.ini --exclude *.rating --exclude *.bat --exclude *.json --exclude *.optkr phigrospack:/ . && exit"
start cmd /k "cd Project Sekai && rclone sync -P --exclude *.ini --exclude *.rating --exclude *.bat --exclude *.json --exclude *.optkr prosekataiko:/ . && exit"
start cmd /k "cd Ryuto Setsujin Customs && rclone sync -P --exclude *.ini --exclude *.rating --exclude *.bat --exclude *.json --exclude *.optkr ryutocustoms:/ . && exit"
start cmd /k "cd Sadkay Charts && rclone sync -P --exclude *.ini --exclude *.rating --exclude *.bat --exclude *.json --exclude *.optkr sadkay:/ . && exit"
start cmd /k "cd Sakurada Customs && rclone sync -P --exclude *.ini --exclude *.rating --exclude *.bat --exclude *.json --exclude *.optkr sakuradacustoms:/ . && exit"
start cmd /k "cd Shoxk Customs && rclone sync -P --exclude *.ini --exclude *.rating --exclude *.bat --exclude *.json --exclude *.optkr shoxkcustoms:/ . && exit"
start cmd /k "cd Taiko ESE && rclone sync -P --exclude *.ini --exclude *.rating --exclude *.bat --exclude *.json --exclude *.optkr taikoese:/ . && exit"
start cmd /k "cd Tang Customs && rclone sync -P --exclude *.ini --exclude *.rating --exclude *.bat --exclude *.json --exclude *.optkr tangcustoms:/ . && exit"
start cmd /k "cd Ugyuu Charts && rclone sync -P --exclude *.ini --exclude *.rating --exclude *.bat --exclude *.json --exclude *.optkr ugyuucustoms:/ . && exit"
start cmd /k "cd WilliamDavi Charts && rclone sync -P --exclude *.ini --exclude *.rating --exclude *.bat --exclude *.json --exclude *.optkr williamdavicustoms:/ . && exit"
start cmd /k "cd Yokoyoko Customs && rclone sync -P --exclude *.ini --exclude *.rating --exclude *.bat --exclude *.json --exclude *.optkr yokocustoms:/ . && exit"


